In [14]:
import pandas as pd
pd.set_option('display.max_columns', None)
key_cols = ['LastPrice', 'Volume', 'Turnover', 'BPrice1', 'BVol1', 'SPrice1', 'SVol1', 'BPrice2', 'BVol2', 'SPrice2', 'SVol2', 'BPrice3', 'BVol3', 'SPrice3', 'SVol3', 'SPrice4', 'BVol4', 'SPrice4', 'SVol4', 'BPrice5', 'BVol5', 'SPrice5', 'SVol5']

# IF 沪深300指数期货
df = pd.read_pickle('2023.07.20/CFFEX_IF2307')
df['ReceiveTime'] = pd.to_datetime(df['ReceiveTime'], unit='us').dt.tz_localize(tz='UTC').dt.tz_convert(tz='Asia/Shanghai') 
df = df.set_index('ReceiveTime')[key_cols]

display(df.head())
df.describe()

,LastPrice,Volume,Turnover,BPrice1,BVol1,SPrice1,SVol1,BPrice2,BVol2,SPrice2,SVol2,BPrice3,BVol3,SPrice3,SVol3,SPrice4,BVol4,SPrice4,SVol4,BPrice5,BVol5,SPrice5,SVol5
ReceiveTime,,,,,,,,,,,,,,,,,,,,,,,
2023-07-20 09:29:00.089804+08:00,3867.2,132,153141120.0,3867.0,1,3868.0,2,3866.6,1,3868.2,2,3866.2,1,3869.0,8,3869.2,10,3869.2,2,3865.8,12,3869.6,1
2023-07-20 09:30:00.510201+08:00,3867.2,173,200713440.0,3868.0,2,3869.0,10,3867.2,7,3869.2,2,3866.0,6,3869.4,1,3869.6,12,3869.6,3,3865.2,2,3869.8,4
2023-07-20 09:30:01.012329+08:00,3868.0,219,254090340.0,3867.2,2,3868.0,8,3866.0,6,3868.8,12,3865.8,12,3869.0,12,3869.2,2,3869.2,2,3865.0,1,3869.4,1
2023-07-20 09:30:01.509432+08:00,3868.0,240,278456280.0,3866.0,5,3867.0,1,3865.2,2,3867.2,3,3865.0,1,3868.0,3,3868.8,2,3868.8,4,3863.2,1,3869.0,14
2023-07-20 09:30:02.012558+08:00,3866.4,258,299338620.0,3866.2,7,3867.0,2,3866.0,5,3867.2,3,3865.8,1,3867.6,1,3868.0,2,3868.0,3,3865.0,1,3868.8,4

,LastPrice,Volume,Turnover,BPrice1,BVol1,SPrice1,SVol1,BPrice2,BVol2,SPrice2,SVol2,BPrice3,BVol3,SPrice3,SVol3,SPrice4,BVol4,SPrice4,SVol4,BPrice5,BVol5,SPrice5,SVol5
count,25693.000000,25693.000000,2.569300e+04,25693.000000,25693.000000,25693.000000,25693.000000,25693.000000,25693.000000,25693.000000,25693.000000,25693.000000,25693.000000,25693.000000,25693.000000,25693.000000,25693.000000,25693.000000,25693.000000,25693.000000,25693.000000,25693.000000,25693.000000
mean,3852.738769,22368.628187,2.592365e+10,3852.520780,2.694391,3852.952135,3.062663,3852.283315,3.362706,3853.192504,3.653641,3852.050162,3.381193,3853.419834,3.920601,3853.646557,3.257813,3853.646557,3.927957,3851.562418,3.172537,3853.877476,3.915541
std,13.527314,9436.210019,1.091081e+10,13.530648,2.385216,13.521804,3.668707,13.536279,2.785685,13.513007,3.907605,13.548057,2.791726,13.502004,4.014763,13.486644,2.653641,13.486644,3.671870,13.594754,2.730387,13.467240,3.897681
min,3818.000000,132.000000,1.531411e+08,3818.000000,1.000000,3818.200000,1.000000,3817.200000,1.000000,3818.400000,1.000000,3816.000000,1.000000,3818.600000,1.000000,3818.800000,1.000000,3818.800000,1.000000,3813.000000,1.000000,3819.000000,1.000000
25%,3850.400000,14952.000000,1.735389e+10,3850.200000,1.000000,3850.600000,1.000000,3850.000000,2.000000,3850.800000,1.000000,3849.800000,2.000000,3851.000000,2.000000,3851.200000,1.000000,3851.200000,2.000000,3849.400000,1.000000,3851.400000,2.000000
50%,3855.600000,22295.000000,2.584758e+10,3855.400000,2.000000,3855.800000,2.000000,3855.200000,3.000000,3856.000000,3.000000,3855.000000,3.000000,3856.400000,3.000000,3856.600000,3.000000,3856.600000,3.000000,3854.600000,2.000000,3856.800000,3.000000
75%,3860.400000,29545.000000,3.423563e+10,3860.200000,3.000000,3860.600000,4.000000,3860.000000,4.000000,3860.800000,4.000000,3859.800000,4.000000,3861.000000,5.000000,3861.400000,4.000000,3861.400000,5.000000,3859.200000,4.000000,3861.600000,5.000000
max,3881.400000,39880.000000,4.611521e+10,3881.400000,47.000000,3881.600000,52.000000,3880.800000,47.000000,3881.800000,53.000000,3880.600000,47.000000,3882.000000,53.000000,3882.200000,56.000000,3882.200000,57.000000,3880.200000,56.000000,3882.600000,57.000000

In [15]:
# IO 沪深300股指期权
df = pd.read_pickle('2023.07.20/CFFEX_IO2307-C-3800')
df['ReceiveTime'] = pd.to_datetime(df['ReceiveTime'], unit='us').dt.tz_localize(tz='UTC').dt.tz_convert(tz='Asia/Shanghai') 
df = df.set_index('ReceiveTime')[key_cols]

display(df.head(10))
df.describe()

,LastPrice,Volume,Turnover,BPrice1,BVol1,SPrice1,SVol1,BPrice2,BVol2,SPrice2,SVol2,BPrice3,BVol3,SPrice3,SVol3,SPrice4,BVol4,SPrice4,SVol4,BPrice5,BVol5,SPrice5,SVol5
ReceiveTime,,,,,,,,,,,,,,,,,,,,,,,
2023-07-20 09:29:00.095337+08:00,60.0,6,36000.0,58.6,3,60.0,16,58.4,1,63.4,1,58.0,4,65.0,3,66.0,6,66.0,1,56.4,1,66.6,1
2023-07-20 09:30:00.515360+08:00,65.0,24,144840.0,62.0,5,65.0,2,61.0,2,65.8,13,60.2,22,66.0,1,66.2,6,66.2,1,59.2,1,66.6,1
2023-07-20 09:30:01.017024+08:00,65.8,28,171000.0,62.2,3,65.8,11,62.0,5,66.0,1,61.0,2,66.2,1,66.6,1,66.6,1,60.2,25,66.8,2
2023-07-20 09:30:01.514086+08:00,65.8,30,184160.0,65.0,1,65.8,9,62.2,3,66.0,1,62.0,5,66.2,1,66.4,1,66.4,1,61.0,2,66.6,1
2023-07-20 09:30:02.015980+08:00,65.6,32,197220.0,65.2,3,65.6,1,65.0,1,65.8,9,62.0,5,66.0,1,66.2,2,66.2,1,60.6,2,66.4,1
2023-07-20 09:30:02.513824+08:00,65.2,43,269340.0,65.2,3,65.8,3,62.0,5,66.0,1,61.0,2,66.2,1,66.4,2,66.4,1,60.2,26,66.6,1
2023-07-20 09:30:03.013466+08:00,65.8,48,302260.0,65.0,1,66.2,1,62.2,3,66.4,1,62.0,5,66.6,1,66.8,2,66.8,2,60.6,2,67.0,1
2023-07-20 09:30:03.514150+08:00,65.8,60,382440.0,65.4,2,68.8,1,65.2,3,69.0,1,65.0,2,69.4,1,70.0,1,70.0,5,62.0,5,70.8,1
2023-07-20 09:30:04.013357+08:00,65.8,60,382440.0,65.6,11,68.0,1,65.4,2,68.8,1,65.0,2,69.0,1,69.4,1,69.4,1,62.0,5,70.0,5
2023-07-20 09:30:04.512571+08:00,65.8,60,382440.0,65.8,3,68.0,1,65.6,8,68.8,1,65.0,2,69.0,1,69.4,1,69.4,1,63.2,1,70.0,5

,LastPrice,Volume,Turnover,BPrice1,BVol1,SPrice1,SVol1,BPrice2,BVol2,SPrice2,SVol2,BPrice3,BVol3,SPrice3,SVol3,SPrice4,BVol4,SPrice4,SVol4,BPrice5,BVol5,SPrice5,SVol5
count,27824.000000,27824.000000,2.782400e+04,27824.000000,27824.000000,27824.000000,27824.000000,27824.000000,27824.000000,27824.000000,27824.000000,27824.000000,27824.000000,27824.000000,27824.000000,27824.000000,27824.000000,27824.000000,27824.000000,27824.000000,27824.000000,27824.000000,27824.000000
mean,54.994077,7355.733755,4.595622e+07,54.650331,8.800640,55.313327,9.124497,54.408683,12.677545,55.550582,13.322923,54.193588,17.695443,55.763248,16.061098,55.970112,19.403860,55.970112,19.650086,53.772355,16.688291,56.182612,17.564764
std,11.681356,3686.332380,1.966783e+07,11.673951,8.220454,11.699939,8.221520,11.671638,9.657088,11.708212,9.939698,11.667137,10.367837,11.713749,9.911273,11.716662,10.030756,11.716662,9.662365,11.656497,9.329622,11.719690,9.486457
min,24.600000,6.000000,3.600000e+04,24.200000,1.000000,25.000000,1.000000,24.000000,1.000000,25.200000,1.000000,23.800000,1.000000,25.400000,1.000000,25.600000,1.000000,25.600000,1.000000,23.200000,1.000000,25.800000,1.000000
25%,53.000000,4533.750000,3.130374e+07,52.400000,2.000000,53.200000,3.000000,52.200000,6.000000,53.400000,6.000000,52.000000,9.000000,53.600000,9.000000,53.800000,12.000000,53.800000,12.000000,51.600000,9.000000,54.000000,11.000000
50%,57.000000,6856.000000,4.441790e+07,56.800000,6.000000,57.400000,7.000000,56.400000,10.000000,57.600000,12.000000,56.200000,16.000000,57.800000,15.000000,58.000000,18.000000,58.000000,19.000000,55.800000,15.000000,58.200000,16.000000
75%,61.800000,9730.000000,6.103410e+07,61.400000,13.000000,62.000000,13.000000,61.200000,18.000000,62.400000,19.000000,61.000000,24.000000,62.600000,22.000000,62.800000,26.000000,62.800000,26.000000,60.600000,22.000000,63.000000,24.000000
max,81.000000,15635.000000,8.218128e+07,81.000000,65.000000,81.600000,92.000000,80.600000,85.000000,81.800000,101.000000,80.400000,85.000000,82.000000,100.000000,82.200000,86.000000,82.200000,94.000000,80.000000,85.000000,82.400000,80.000000